### ISSUE TITLE
Nifi nar isn't build

### ISSUE THREAD

**Issue by igbayilola** [orendain/trucking-iot#2]
Hello,
I have an issue with the Nifi nar. The following error:
cp: cannot stat ‘/home/nifi/trucking-iot-master/nifi-bundle/nifi-trucking-nar/target/nifi-trucking-nar-0.5.4.nar’: No such file or directory.
The file isn't anywhere. I just change the list of drivers and the routes to use the getTruckingData processor.
Thanks in advance.

**Comment by orendain** [comment]
@igbayilola Heya! :)  Have you tried building the nar first?

Run this script: https://github.com/orendain/trucking-iot/blob/master/scripts/builds/nifi-bundle.sh

**Comment by igbayilola** [comment]
@orendain Thanks you for answering. I did. Its the script run that give me the error. 

sbt nifiBundle/compile shows **success**

cp -f $projDir/trucking-nifi-bundle/nifi-trucking-nar/target/nifi-trucking-nar-$projVer.nar $nifiLibDir fails with the following error **cp: cannot stat ‘/home/nifi/trucking-iot-master/nifi-bundle/nifi-trucking-nar/target/nifi-trucking-nar-0.5.4.nar’: No such file or directory.**

I'm doing this beacause I change some conf, the drivers list and the routes to correspond to my country.

Thanks you again for your job.

**Comment by orendain** [comment]
@igbayilola The project must not have built correctly.  Can you cd into the root /trucking-iot directory and run `sbt nifiBundle/compile`

**Comment by orendain** [comment]
Hmm ... that directory isn't the one in the script.  Could you make sure that the directory `/home/nifi/trucking-iot-master/nifi-bundle/nifi-trucking-nar/` even exists?  The directory in the script above expects `/trucking-nifi-bundle/nifi-trucking-nar/`

**Comment by igbayilola** [comment]
@orendain  I forgot to say. After many fails, I see that the **trucking-nifi-bundle** doesn't exist and it is **nifi-bundle**. So I modify the script to 
**cp -f $projDir/nifi-bundle/nifi-trucking-nar/target/nifi-trucking-nar-$projVer.nar $nifiLibDir**

The **nifi-bundle/nifi-trucking-nar/** just have pom.xml inside.

**Comment by orendain** [comment]
@igbayilola Ah, good catch - I can't believe I missed that.

Instead of `sbt nifiBundle/compile`, run `sbt nifiBundle/package`

**Comment by igbayilola** [comment]
@orendain Thanks you. It has work. But the drivers names and route are still the same.
I fainaly find a way. Copy the modified conf and routes (reference.conf and routes directory) in **/var/lib/nifi/work/nar/extensions/nifi-trucking-nar-$projVer.nar-unpacked/META-INF/bundled-dependencies/**

Thanks.
